version: '3.8'

services:
  studentcoins_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studentcoins_php
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "9000"
    networks:
      - studentcoins

  studentcoins_nginx:
    image: nginx:stable-alpine
    container_name: studentcoins_nginx
    expose:
        - "8080"
    ports:
      - "8088:8080"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - studentcoins_php
    networks:
      - studentcoins

  studentcoins_db:
    image: mysql:8.0
    container_name: studentcoins_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - studentcoins

volumes:
  dbdata:

networks:
  studentcoins:
    driver: bridge
